project:
  type: website

website:
  title: "Tingwei Wu"
  navbar:
    right:
      - href: index.qmd
        text: Landing page
      - href: projects.qmd
        text: Project page
      - href: about.qmd
        text: About page
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto