project:
  type: website

website:
  title: "Tingwei Wu"
  navbar:
    right:
      - href: index.qmd
        text: Landing page
      - about.qmd
      - href: projects.qmd
        text: Project page

format:
  html:
    theme:
      - Lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto